server:
  port: 9090
  tomcat:
    max-threads: 30
  use-forward-headers: true

logging:
  level:
    ROOT: INFO

## management endpoints are disabled, except for /info, /health and /prometheus
management:
  endpoint:
    health:
      show-details: when_authorized
  endpoints:
    web:
      base-path: /
      exposure:
        include: health,info,loggers,metrics,prometheus
      path-mapping:
        loggers: api/v1/admin/loggers

# database
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/minesweeper?createDatabaseIfNotExist=true&verifyServerCertificate=false&useSSL=false}
    hikari:
      jdbc-url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/minesweeper?createDatabaseIfNotExist=true&verifyServerCertificate=false&useSSL=false}
      username: ${SPRING_DATASOURCE_USERNAME:root}
      password: ${SPRING_DATASOURCE_PASSWORD:password}
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    open-in-view: false
  data:
    jpa:
      repositories:
        bootstrap-mode: deferred
      show-sql: false
      properties:
        hibernate:
          format_sql: false
    rest:
      base-path: /api/v1
  main:
    allow-bean-definition-overriding: true
